package src;

public enum Amenities {
    FREE_WIFI,
    ROOM_SERVICE,
    POOL,
    FREE_BREAKFAST,
    MINI_FRIDGE,
    TWENTY_FOUR_HOUR_GUEST_RECEPTION,
    LAUNDRY_SERVICES,
    SPA,
    SAUNA,
    GYM,
    BATHROBES,
    BAR,
    HAIR_TOOLS,
    MICROWAVE,
    CLOTHING_IRON,
    ON_SITE_PARKING
}